### ISSUE TITLE
Navigation klappt Menüpunkte in 4. Ebene nicht korrekt aus

### ISSUE THREAD

**Issue by cliffparnitzky** [contao-themes-net/nature-theme-bundle#1]
Wenn man Seiten auf der 4. Ebene hat, werden diese in der Navigation nicht korrekt dargestellt. Die List klappt gleich mit der 3. Ebene aus und überdeckt die 3. Ebene (siehe Screenshot).

![image](https://user-images.githubusercontent.com/1247552/70706278-e5f6f400-1cd5-11ea-97ba-1b41523ef79a.png)

**Comment by seibtph** [comment]
Behoben in Version 1.3.1
