### ISSUE TITLE
In elements.css 221: i {    color: $primary;     }  blockiert has-text-link Einträge für Icons im Inhaltscontainer

### ISSUE THREAD

**Issue by magicsepp** [contao-themes-net/nature-theme-bundle#10]
quick-fix
221:
/*    i {
      color: $primary;
    } */

Beispielcode:
<div class="ce_ct_featureElement block">
<div class="icon has-text-link">
      <i class="fa fa-map-marker-alt fa-2x "></i>
    </div>
</div>

**Comment by seibtph** [comment]
Behoben in Version 1.3.1
