### ISSUE TITLE
Bild mit Bildunterschrift im Container zentrieren

### ISSUE THREAD

**Issue by Timo-Kite** [contao-themes-net/nature-theme-bundle#13]
Contao 4.9.3
NATURE Theme 1.3.1
Hallo,
Ich möchte Bilder mit Bildunterschrift in jedem Container horizontal zentrieren.
Über die **Erweiterte CSS-Klassen** klappt das leider nicht.
Siehe PDF

MfG Timo

[Frontend - Backend.pdf](https://github.com/contao-themes-net/nature-theme-bundle/files/4885737/Frontend.-.Backend.pdf)

**Comment by seibtph** [comment]
fixed in version 1.3.2
