### ISSUE TITLE
Unknown column 'com_template' in 'field list'

### ISSUE THREAD

**Issue by internethering** [contao-themes-net/nature-theme-bundle#14]
Hallo, beim Versuch unter Contao 4.10.0 das Nature Theme zu installieren, ist es mir nicht möglich, das Template zu importieren:

> Der Import konnte nicht abgeschlossen werden! Ist die Datenbank aktuell und die Template-Datei kompatibel mit Ihrer Contao-Version?

Datenbank hab ich davor aktualisiert. Das Logging sagt mir:

> [2020-08-26 20:10:56] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO `tl_content` (`id`, `pid`, `ptable`, `sorting`, `tstamp`, `type`, `headline`, `text`, `addImage`, `inline`, `overwriteMeta`, `singleSRC`, `alt`, `imageTitle`, `size`, `imagemargin`, `imageUrl`, `fullsize`, `caption`, `floating`, `html`, `listtype`, `listitems`, `tableitems`, `summary`, `thead`, `tfoot`, `tleft`, `sortable`, `sortIndex`, `sortOrder`, `mooHeadline`, `mooStyle`, `mooClasses`, `highlight`, `code`, `url`, `target`, `overwriteLink`, `titleText`, `linkTitle`, `embed`, `rel`, `useImage`, `multiSRC`, `orderSRC`, `useHomeDir`, `perRow`, `perPage`, `numberOfItems`, `sortBy`, `metaIgnore`, `galleryTpl`, `customTpl`, `playerSRC`, `youtube`, `vimeo`, `posterSRC`, `playerSize`, `playerOptions`, `playerStart`, `playerStop`, `playerCaption`, `playerAspect`, `splashImage`, `playerPreload`, `playerColor`, `youtubeOptions`, `vimeoOptions`, `sliderDelay`, `sliderSpeed`, `sliderStartSlide`, `sliderContinuous`, `cteAlias`, `articleAlias`, `article`, `form`, `module`, `protected`, `groups`, `guests`, `cssID`, `invisible`, `start`, `stop`, `tabs_element`, `tabs_navigation`, `ct_sliderElement_backgroundImageSRC`, `ct_sliderElement_playerSRC`, `ct_sliderElement_subHeadline`, `ct_sliderElement_target`, `ct_sliderElement_linkText`, `ct_sliderElement_page`, `ct_wrapper_name`, `ct_teaserBox_customTpl`, `ct_teaserBox_pageTitle`, `ct_teaserBox_pageText`, `ct_teaserBox_page`, `ct_priceBox_customTpl`, `ct_popularPriceBox`, `ct_priceBox_linkText2`, `ct_priceBox_link2`, `ct_priceBox_linkText1`, `ct_priceBox_link1`, `ct_priceLabel`, `ct_price`, `ct_featureElement_customTpl`, `ct_iconLink`, `ct_featureIcon`, `ct_contentBox_customTpl`, `ct_contentBox_pageTitle`, `ct_contentBox_pageText`, `ct_contentBox_page`, `advancedCss`, `cssStyleSelector`, `textModal_customTpl`, `textModal_content`, `com_template`, `com_requireLogin`, `com_disableCaptcha`, `com_bbcode`, `com_moderate`, `com_perPage`, `com_order`) VALUES(2, 1, 'tl_article', 128, 1567682907, 'sliderStart', 'a:2:{s:4:\\\"unit\\\";s:2:\\\"h2\\\";s:5:\\\"value\\\";s:0:\\\"\\\";}', NULL, '', '', '', NULL, '', '', '', '', '', '', '', 'above', NULL, '', NULL, NULL, '', '', '', '', '', 0, 'ascending', '', '', '', '', NULL, '', '', '', '', '', '', '', '', NULL, NULL, '', 4, 0, 0, '', '', '', '', NULL, '', '', NULL, '', NULL, 0, 0, '', 'none', '', '', '', NULL, NULL, 0, 300, 0, '1', 0, 0, 0, 0, 0, '', NULL, '', 'a:2:{i:0;s:0:\\\"\\\";i:1;s:40:\\\"full-width-height-slider parallax-slider\\\";}', '', '', '', NULL, NULL, NULL, NULL, '', '', '', '', NULL, '', NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, '', '', '', NULL, '', '', NULL, NULL, NULL, '', 0x613a323a7b693a303b733a323a223130223b693a313b733a313a2231223b7d, '', NULL, 'com_default', '', '', '', '', 0, 'ascending');\n':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'com_template' in 'field list' at /www/htdocs/xxxxxx/yyyyyy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'com_template' in 'field list' at /www/htdocs/xxxxxx/yyyyyy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:83, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'com_template' in 'field list' at /www/htdocs/xxxxxx/yyyyyy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78)"} []

**Comment by seibtph** [comment]
Hallo @internethering,

ich habe es eben nochmal getestet und konnte die SQL-Datei importieren. Hast du wirklich die richtige SQL-Datei importiert?

Das Feld com_template kommt von Contaos Kommentar-Bundle. Wenn du die minimale Contao-Installation (ohne Kommentare, News, Events etc.) ausgewählt hast, musst du die Datei `nature_theme_contao_demo_4.10.x_minimal_installtool.sql` auswählen, ansonsten die `nature_theme_contao_demo_4.10.x_installtool.sql`.
