### ISSUE TITLE
Frage vor dem Kauf zum Grid 

### ISSUE THREAD

**Issue by landzone21** [contao-themes-net/nature-theme-bundle#15]
Welche Anpassungen am Grid wurden gegenüber dem Bulma-Framework vorgenommen? Wenn ich das Raster von Bulma mit NATURE vergleiche, sind diese unterschiedlich. Ist die Spalten und Abstandsgröße irgendwo einsehbar? In der Demo haben bestimmte Spalten Größen mit Nachkommastellen. Wie ist der Grundgedanke oder das Konzept hierzu, welches Raster kann man grafisch zugrundelegen?

**Comment by seibtph** [comment]
Hallo,

wir haben an dem Grid von Bulma nichts verändert. Was genau meinst du ist unterschiedlich?

**Comment by seibtph** [comment]
Ich schließe den Issue mal. Falls noch Fragen bestehen, gern wieder öffnen oder eine Mail an support@pdir.de senden.
