### ISSUE TITLE
Text Modal Element funktioniert nur im Green Scheme

### ISSUE THREAD

**Issue by Babelfisch** [contao-themes-net/nature-theme-bundle#2]
Das Text Modal Element wird nur im Green-Scheme richtig angezeigt. In anderen Schemes wird der Text und eine Checkbox unter dem Bild angezeigt und für das PopUp muss man die Checkbox anwählen.

https://nature.contao-themes.net/theme-elemente.html?colour=dark-blue

**Comment by seibtph** [comment]
Danke für den Hinweis. Der Fehler ist in der NATURE Theme Demo nun gefixt. Der Fehler betraf übrigens nur die Demo-Seite, wenn man das NATURE Theme also installiert hat funktioniert das Element auch in allen anderen Farbschemen.
