### ISSUE TITLE
Nature Theme mit Contao 4.11 scheinen sich noch nicht zu mögen

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/nature-theme-bundle#21]
- Conclusion: don't install contao-themes-net/nature-theme-bundle 1.4.1 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/config v4.4.19 (conflict analysis result)
    - contao/manager-bundle 4.11.0 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.3].
    - contao/manager-bundle 4.11.0 conflicts with symfony/config v4.4.1.
    - contao/manager-bundle 4.11.0 conflicts with symfony/config v4.4.0.
    - contao/manager-bundle is locked to version 4.11.0 and an update of this package was not requested.
    - Conclusion: don't install symfony/http-kernel v5.2.2 (conflict analysis result)
    - Root composer.json requires contao-themes-net/nature-theme-bundle ^1.4 -> satisfiable by contao-themes-net/nature-theme-bundle[1.4.0, 1.4.1].
    - contao-themes-net/nature-theme-bundle 1.4.0 requires symfony/config 4.4.* -> satisfiable by symfony/config[v4.4.0, ..., v4.4.19].
    - symfony/config[v4.4.2, ..., v4.4.18] conflict with symfony/http-kernel v5.2.0.
    - symfony/web-profiler-bundle v5.2.3 requires symfony/http-kernel ^5.2 -> satisfiable by symfony/http-kernel[v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - Conclusion: don't install symfony/http-kernel v5.2.1 (conflict analysis result)

**Comment by seibtph** [comment]
gefixt mit Version 1.4.2
