### ISSUE TITLE
_custom_colors.scss 404

### ISSUE THREAD

**Issue by webfarben** [contao-themes-net/nature-theme-bundle#24]
Ihr Lieben,

will ich die bearbeite scss speichern bekomme ich ein 404...
binde ich die Dateien im Seitenlayout ein, wird die Seite nicht mehr geladen. "Es ist ein Fehler aufgetreten"

var/log:

`request.CRITICAL: Uncaught PHP Exception ScssPhp\ScssPhp\Exception\CompilerException: "`color_schemes/nature_blue_colors` file not found for @import: _custom_colors.scss on line 15, at column 1" at /var/www/vhosts/ed-pruehs.de/httpdocs/vendor/scssphp/scssphp/src/Compiler.php line 5602 {"exception":"[object] (ScssPhp\\ScssPhp\\Exception\\CompilerException(code: 0): `color_schemes/nature_blue_colors` file not found for @import: _custom_colors.scss on line 15, at column 1 at /var/www/vhosts/ed-pruehs.de/httpdocs/vendor/scssphp/scssphp/src/Compiler.php:5602)"} []`

**Comment by magicsepp** [comment]
Hallo Dirk,

wie sieht den die Änderung in der _custom_colors.scss aus (eventuell ein Leezeichen am Zeilenanfang?) Das Verhalten kann ich aktuell nicht nachvollziehen. Selber benutze ich zwar die Rote Farb Variante aber ich kann das problemlos in Blau ändern.

**Comment by webfarben** [comment]
Servus magicsepp,

ich habe die Änderungen laut Doku gemacht. Aber das kann nicht das Problem verursachen, denn ich kann Änderungen nicht speichern, da ich dann ein 404 bekomme.

Muss ich den die SCSS Dateien überhaupt im Layout einbinden?

**Comment by seibtph** [comment]
@webfarben Konntest du das Problem mittlerweile lösen? Ich schließe das Ticket erstmal, falls du noch Probleme hast kannst du gern nochmal schreiben und es wieder öffnen.
