### ISSUE TITLE
Abandoned Packages

### ISSUE THREAD

**Issue by darkness08** [contao-themes-net/nature-theme-bundle#25]
Beim aktualisieren von Paketen im Nature-Theme habe ich folgende Warnungen erhalten:
```

Package league/uri-hostname-parser is abandoned, you should avoid using it. No replacement was suggested.
Package league/uri-schemes is abandoned, you should avoid using it. No replacement was suggested.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
```
Bisher läuft noch alles. Aber vielleicht gibt es Alternativen für zukünftige Aktualisierungen ?

**Comment by MDevster** [comment]
Danke für den Hinweis, dies sind teilweise Abhängigkeiten anderer Erweiterungen, in zukünftigen Versionen werden die Entwickler diese sicherlich entsprechend ersetzen.
