### ISSUE TITLE
Installing problems

### ISSUE THREAD

**Issue by idiotenpony** [contao-themes-net/nature-theme-bundle#28]
I've been trying to install the Nature Theme for days. However, every time I get this error:
`Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 442368 bytes)`

I have already adjusted the memory limit in .htaccess and the server is completely empty, so there is definitely enough space.

Any ideas?
I'm still a complete newbie and I'm losing all motivation right now x.x

**Comment by seibtph** [comment]
Hey @idiotenpony,

have you activated the Composer Resolver Cloud (Settings Icon -> System Check -> Change Server Configuration -> Use the Composer Resolver Cloud)?

**Comment by idiotenpony** [comment]
Yep, checked it twice ^^

**Comment by MDevster** [comment]
Were you able to solve the problem? Feel free to open the ticket again if you still need help.
