### ISSUE TITLE
Contao 4.9 - Mehrspaltige Newsbeiträge werden nur noch in einer Spalte angezeigt. 

### ISSUE THREAD

**Issue by mrbjoernson** [contao-themes-net/nature-theme-bundle#32]
Hallo, ich habe ein Update von einer bestehenden Website mit Contao 4.4 und Nature-Theme auf Contao 4.9 gemacht. Die Erweiterung Nature-Theme habe ich ebenfalls auf 1.6 geupdatet.

Leider zeigt werden die mehrspaltigen Newsbeiträge nur noch untereinander anzeigt. Es handelt sich um folgende Seite: [https://ud.ddr-studie.de/aktuelles.html](https://ud.ddr-studie.de/aktuelles.html). Ursprünglich sah es so aus: [https://ddr-studie.de/aktuelles.html](https://ddr-studie.de/aktuelles.html) 

Habt ihr zufällig eine Idee woran es liegen könnte?

Vielen Dank und beste Grüße

Björn

**Comment by seibtph** [comment]
Hallo Björn,

hast du das Problem mittlerweile beheben können? Bei mir tritt das auf deiner Seite und auch bei unserer Demo nicht auf.

**Comment by mrbjoernson** [comment]
Vielen Dank für die schnelle Rückmeldung.

Aus irgendeinem Grund hatte ich zwei mal die selben Links gepostet. Bei beiden funktioniert es ;). Auf der folgenden Seite kann man nun erkennen, dass die Newsbeiträge nur einspaltig dargestellt werden: [https://ddr-studie.de/aktuelles.html](https://ddr-studie.de/aktuelles.html)

**Comment by mrbjoernson** [comment]
Update: 
So ich habs, der Teufel steckte mal wieder im Detail. Aus irgendeinem Grund hatte ich das Ganze als Modul Nachrichtenarchiv angelegt. Es funktionierte bisher auch in Contao 4.4. Nun in Contao 4.9 nicht mehr. 

Als Nachrichtenliste, wie es auch bei euch im Template angelegt ist, klappt es nun wieder. Und für meinen Zweck reicht die Liste auch aus.
