### ISSUE TITLE
PHP8 noch nicht unterstützt?

### ISSUE THREAD

**Issue by Punktraum** [contao-themes-net/nature-theme-bundle#33]
Hallo

Ich wollte gerne mal das Nature Theme für die Erneuerung/Aktualisierung unserer Club-Website testen.
Der Webserver läuft mit PHP 8, wenn ich das Theme aber über den Contao Manager installieren will, reklamiert die Installation, dass diese PHP Version nicht unterstützt werde.

```
Problem 1
    - contao-themes-net/nature-theme-bundle is locked to version 1.6.0 and an update of this package was not requested.
    - contao-themes-net/nature-theme-bundle 1.6.0 requires php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
```

Habe den Server nun auf PHP 7.4 umgestellt, dann gehts natürlich. 

Trotzdem aber die Frage; wird PHP 8 in Bälde unterstützt?

Besten Dank und Gruss
Andreas

**Comment by MDevster** [comment]
fixed in version 1.7.0

**Comment by Punktraum** [comment]
Habe das Nature Theme nun unter PHP 8 installiert, die Installation klappt und das Backend funktioniert.
Ich habe eine jungfräuliche Contao Installation gemacht (Contao 4.12.3,  Contao Manager 1.4.10) und das Theme gem. Dokumentation installiert. 

Im Frontend erhalte ich jedoch die folgende Fehlermeldung (var/logs):
`[2021-11-19T14:08:09.507284+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Contao\Template::insert(): Argument #2 ($data) must be of type ?array, string given, called in /home/httpd/vhosts/account/tld/vendor/contao/core-bundle/src/Resources/contao/templates/image/image.html5 on line 7" at /home/httpd/vhosts/account/tld/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php line 317 {"exception":"[object] (TypeError(code: 0): Contao\\Template::insert(): Argument #2 ($data) must be of type ?array, string given, called in /home/httpd/vhosts/account/tld/vendor/contao/core-bundle/src/Resources/contao/templates/image/image.html5 on line 7 at /home/httpd/vhosts/account/tld/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:317)"} []`

Woran könnte das liegen?
Die Verzeichnisse in der Medienverwaltung sind auf "öffentlich" gestellt.

**Comment by seibtph** [comment]
Hallo @Punktraum,

hast du evtl. mal einen Contao-Zugang für uns? Bitte gern an support[at]pdir.de senden. Dann kann ich gern mal schauen woran das liegt.

In unserer Testumgebung hatte ich die Fehlermeldung unter PHP 8 nicht, deswegen kann ich gerade noch nicht sagen woran das liegt.

**Comment by Punktraum** [comment]
Hallo Philipp

Ich habe Dir einen Account (Admin) eingerichtet, Credentials sende ich Dir per E-Mail an p*.s*@gmail.com.
