### ISSUE TITLE
Contao 4.13.0 - Frontend: Es ist ein Fehler aufgetreten

### ISSUE THREAD

**Issue by MichaelSFD** [contao-themes-net/nature-theme-bundle#41]
Hallo,

ich habe "Nature 1.8.0" unter Contao 4.13.0 wie in der Dokumentation beschrieben installiert. Die Installation brachte keine Fehlermeldungen.

Will man aber das Frontend aufrufen, kommt bei jeder Seite die Contao-Fehlerseite "Es ist ein Fehler aufgetreten".

Mir ist aufgefallen, dass es in der Dateiverwaltung zwar den Ordner "naturetheme" gibt, dieser ist aber leer. Somit ist also schonmal kein "Styling" vorhanden.

Das Ganze habe ich zweimal in eine jeweils komplett jungfräuliche Contao-Installation gemacht. Beide Male mit dem gleichen Ergebnis.

Ich nutze als öffentlichen Ordner "public", nicht "web".
PHP-Version ist 7.4.
Log-Datei in Anlage.

Schon mal vielen Dank und viele Grüße

Michael

[nature-prod-2022-03-01.log](https://github.com/contao-themes-net/nature-theme-bundle/files/8162977/nature-prod-2022-03-01.log)

**Comment by MichaelSFD** [comment]
Hallo,

wie in der Fehlermeldung zu ODD geschrieben, liegt auch dort der gleiche Fehler vor.

Aus einer älteren Test-Installation von ODD hatte ich noch die Daten aus der Dateiverwaltung und habe die einfach mal in die aktuelle Installation hochgeladen.

Und es hat funktioniert.

Der Fehler liegt also bei den fehlenden Dateien  im Ordner "naturetheme".

Viele Grüße

Michael

**Comment by MichaelSFD** [comment]
Hallo Matthias,

ich habe nach den Änderungen das Theme heute installiert - es hat problemlos geklappt.

Einen kleinen Fehler habe ich aber noch gefunden.

Beim Aufruf der Seite "Events" kommt auch die Fehlermeldung "Es ist ein Fehler aufgetreten".

Das scheint am Kalender-Template "cal_default_nature" im Modul "Events / Kalender" zu liegen. Ändert man dies auf "cal_default" wird die Seite angezeigt. Nur stimmt dann die Optik halt nicht so ganz.

Viele Grüße

Michael

**Comment by MDevster** [comment]
Hi, @MichaelSFD bitte teste mal ein Update auf die neue Version 1.8.1, cal_default_nature sollte auf alle Fälle standardmäßig vorhandne sein.

**Comment by MichaelSFD** [comment]
Hallo Matthias,

ich hatte schon 1.8.1 installiert, habe es aber noch einmal neu aufgesetzt.

Der Fehler ist weiterhin vorhanden. Das Template ist vorhanden, enthält aber einen Fehler in Zeile 11 (Anzeige der Wochentage).

Wenn ich die Zeile 11 lösche wird die Seite (ohne Wochentage) angezeigt.

Logdatei in Anlage.

Viele Grüße

Michael

[nature-prod-2022-03-10.log](https://github.com/contao-themes-net/nature-theme-bundle/files/8227464/nature-prod-2022-03-10.log)

**Comment by MDevster** [comment]
Contao removed Patchwork UTF8 (https://github.com/contao/contao/issues/2630), will be solved in Version 1.8.2

**Comment by MDevster** [comment]
@MichaelSFD mit folgender Änderung im Template kannst du bereits weiter arbeiten: https://github.com/contao-themes-net/nature-theme-bundle/commit/7ac5a5c39fdd9adcc29972cfe25878fe3fb32356#diff-02abd2f1704fc86c29a9d59edcfe4661ec0dcd7247536f7d1423046d787dbfa1

**Comment by MichaelSFD** [comment]
Klappt - Vielen Dank !!!
