### ISSUE TITLE
Navigation Untermenü bei Touch

### ISSUE THREAD

**Issue by ovationat** [contao-themes-net/nature-theme-bundle#5]
Hallo Zusammen,

habe für einen Kunden unter www.bit-com.at das Theme in Verwendung. Wir sind soweit sehr zufrieden. 
Leider haben wir ein großes Problem bei der Menü-Navigation mittels Touch in der Desktop-Ansicht unter beispielsweise WIN 10 im Chrome sowie Firefox. Wenn man auf einen Navigationspunkt mit Unterseiten (Untermenü klappt bei hover aus mit Mausverwendung) mit dem Finger tippt, wir sofort die jeweilige Hauptseite (1st Level) geöffnet/geladen, anstatt im ersten Schritt das Untermenü (2nd Level) aufzuklappen und erst beim zweiten tippen die 1st Level Seite zu öffnen. Das macht eine Navigation mittels Touch unmöglich, ich bitte um Info wie wir das Problem lösen können, vielen Dank!

**Comment by seibtph** [comment]
Hallo @ovationat, 

wir werden spätestens am Montag ein Update veröffentlichen, das den Fehler behebt.

**Comment by seibtph** [comment]
Mit der Version 1.2.7 ist dieser Fehler nun behoben.
