### ISSUE TITLE
Full Height Teaserbox lässt keinen Bilderaustausch zu.

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/nature-theme-bundle#50]
Hi,

Im Einsatz Contao 4.13.2 mit Nature Theme möchte ich Bilder im Full Height Teaser austauschen - Error 500

request.CRITICAL: Uncaught PHP Exception TypeError: "unserialize(): Argument #1 ($data) must be of type string, null given" at /var/www/web/vendor/contao-themes-net/theme-components-bundle/src/Element/TeaserBoxElement.php line 55 {"exception":"[object] (TypeError(code: 0): unserialize(): Argument #1 ($data) must be of type string, null given at /var/www/web/vendor/contao-themes-net/theme-components-bundle/src/Element/TeaserBoxElement.php:55)"} []

Danke vorab und VG

**Comment by magicsepp** [comment]
Überprüfe of folgende Code Änderung bei dir noch vorhanden ist.
Die Zeile 55 sollte eigentlich aktuell icht mehr vorhanden sein siehe
https://github.com/contao-themes-net/theme-components-bundle/pull/4

**Comment by mr2017x** [comment]
war tatsächlich noch drin, woher kommt das, dass dies nicht "weggeupdatet" wurde? Danke und GL
