### ISSUE TITLE
1.3.10 unserialize() expects parameter 1 to be string

### ISSUE THREAD

**Issue by magicsepp** [contao-themes-net/nature-theme-bundle#52]
```
- Upgrading contao-themes-net/theme-components-bundle (1.3.9 => 1.3.10): Extracting archive
```
var/log
```
[2022-04-04 17:26:20] request.CRITICAL: Uncaught PHP Exception TypeError: "unserialize() expects parameter 1 to be string, null given" at /www/cto44/vendor/contao-themes-net/theme-components-bundle/src/Element/SliderElement.php line 66 {"exception":"[object] (TypeError(code: 0): unserialize() expects parameter 1 to be string, null given at /www/cto44/vendor/contao-themes-net/theme-components-bundle/src/Element/SliderElement.php:66)"} []
```
line 66 should be:
```if($this->singleSRC) $this->Template->metaImg = FilesModel::findByUuid($this->singleSRC)->meta;```

**Comment by magicsepp** [comment]
Hallo Matthias,

da ist das unserialize noch drin.. ;( 
Mein Vorschlag war:
/contao-themes-net/theme-components-bundle/tree/master/src/Element)/SliderElement.php /
´´´´
- $this->Template->metaImg = unserialize(FilesModel::findByUuid($this->singleSRC)->meta);
oder
+if($this->singleSRC) $this->Template->metaImg = FilesModel::findByUuid($this->singleSRC)->meta;

´´´´
Was ist besser ?

**Comment by MDevster** [comment]
[This ](https://github.com/contao-themes-net/theme-components-bundle/pull/7/files#diff-80575c8cf5e8bdcce03a0c9b41e1ad970a0d7348713cdaa6da7f6a814828bd07R51)is better, will be fixed in version 1.3.11

**Comment by magicsepp** [comment]
Update hat soweit funktioniert, die Seite osz noch erreichbar ;) dafür fehlen jetzt mi BE Informationen in der Vorschau
![grafik](https://user-images.githubusercontent.com/1285182/161796198-bc0c8e17-c230-40ec-adcc-034761e6b9fc.png)

**Comment by magicsepp** [comment]
Danke - mit theme-components-bundle r1.3.12 funktiert die BE Anzeige wieder.
