### ISSUE TITLE
Probleme mit dem Nature Theme

### ISSUE THREAD

**Issue by Clumsy88** [contao-themes-net/nature-theme-bundle#6]
Hallo Zusammen,  

ich hab ein paar Schwierigkeiten mit meinem absoluten Lieblings-Theme für Contao.  Auch nach viel suchen und grübeln habe ich keine Lösung gefunden. 

1. Die Bildergalerien bzw. auch das vergrößern von Bilder funktioniert nicht. Wird eine Foto "angeklickt" erscheint eine minimalisierter Bildbetrachter aber leider kein Bild. Bislang habe ich keine Lösung dafür gefunden.

2. Bei den Feature Boxen mit Icon und Text funktioniert die Verlinkung/Weiterleitung auf eine interne Seite nicht. Im besagten Fall landet man immer auf der Startseite. Umgangen werden kann das Problem durch die vollständige Eingabe der gewünschten URL. Ist aber umständlich

3. Ich bekomme den Belegungsplan von Mailwurm leider nicht ans laufen. In meiner bisherigen Anwendung unter Contao 4.4  (ohne Theme) läuft er ohne Probleme. Vielleicht liegts auch überhaupt nicht am Theme? Nach problemloser Installation und Einrichtung von Kategorie und Objekt erscheint beim erfassen der ersten Buchung folgende Fehlermeldung:

An exception occurred while executing 'INSERT INTO tl_belegungsplan_calender (`author`, `pid`, `tstamp`) VALUES ('1', '3', 0)': SQLSTATE[HY000]: General error: 1364 Field 'ueberschneidung' doesn't have a default value

Danke für eine kurzes Feedback....

Magnus Liebert

**Comment by Clumsy88** [comment]
Update vom 3. Mai 2020 zum Thema Bildergalerie:

Das Problem mit der Bildergalerie oder ganz allgemein mit der Großbilddarstellung von Fotos liegt an den Größenvorgaben für Fotos. In der Großbild-Ansicht werden nur Fotos angezeigt die bestimmte Größenvorgaben (z. B. > 1.000 px) erfüllen. Gut wenn man schöne Fotos am besten in HDQualität hat aber in der Praxis ist man doch bemüht die Fotos für die Website runter zu skalieren. Also nicht ganz praxisgerecht diese Einstellung. Gibt es im Theme eine Einstellung an der man diese Größenvorgaben anpassen kann? Ich arbeite mit der Version 4.9.2 des Nature Themes. 

Danke für ein kurzes Feedback...

Magnus

**Comment by seibtph** [comment]
Hallo Magnus,

ich habe eine neue Version 1.2.9 veröffentlicht, die schonmal den Bug mit der Verlinkung bei den Feature Elementen behebt.

Das Problem mit den Bildergalerien müsste mit der neuesten Version auch bereits behoben sein. In unserer Testumgebung konnte ich mit der neuesten Version und Contao 4.9.2 keine Probleme feststellen. In der Großbild-Ansicht sollten normalerweise auch Bilder unter 1000px angezeigt werden. Damit die Bilder runterskaliert werden, kannst du bei der Bildergalerie ja eine Bildgröße angaben.

Und der letzte Fehler mit dem Belegungsplan dürfte nicht mit unserem Theme zusammenhängen. Da müsstest du dich bitte einmal an die Macher der Erweiterung wenden.

**Comment by Clumsy88** [comment]
Hallo Philipp,



vielen Dank für die schnelle Hilfe. 


Ich hab heute Contao auf 4.9.2 (zuvor4.9.0) umgestellt und Dein Themeupdate 1.2.9 eingespielt.  Das Problem mit der Verlinkung derFeature Elemente ist erledigt 😊. Bilderfunktionieren leider noch nicht.


Das erste Bild mit der HD-Auflösung(1920*1280px) wird in der Großansicht angezeigt. Alle anderen Bilder leidernicht. Schau mal...

 http://www.worx.limbach-ww.de/Limbach.html



Das erste Bild mit der HD-Auflösung(1920*1280px) wird in der Großansicht angezeigt. Alle anderen Bilder leidernicht.

Ist die Bildgröße nicht eine Vorgabe dieirgendwo im Styleguide des Themes angepasst werden kann?

 Danke für ein kurzes Feedback…

 Grüße aus dem Westerwald… 

Magnus









 


    Am Montag, 4. Mai 2020, 15:03:20 MESZ hat Philipp Seibt <notifications@github.com> Folgendes geschrieben:  
 
 


Hallo Magnus,

ich habe eine neue Version 1.2.9 veröffentlicht, die schonmal den Bug mit der Verlinkung bei den Feature Elementen behebt.

Das Problem mit den Bildergalerien müsste mit der neuesten Version auch bereits behoben sein. In unserer Testumgebung konnte ich mit der neuesten Version und Contao 4.9.2 keine Probleme feststellen. In der Großbild-Ansicht sollten normalerweise auch Bilder unter 1000px angezeigt werden. Damit die Bilder runterskaliert werden, kannst du bei der Bildergalerie ja eine Bildgröße angaben.

Und der letzte Fehler mit dem Belegungsplan dürfte nicht mit unserem Theme zusammenhängen. Da müsstest du dich bitte einmal an die Macher der Erweiterung wenden.

**Comment by seibtph** [comment]
Du kannst uns auch gern mal einen Contao Admin-Zugang anlegen und an support@pdir.de senden, dann können wir schauen wo der Fehler liegt.

Sind die Bilder vielleicht zu groß? Die Galerie mit den Theme-Bildern funktioniert ja.

**Comment by seibtph** [comment]
Fehler wurde gelöst, wenn man die Bilder in einen Unterordner von files verschiebt. Wenn Sie direkt unter files liegen funktioniert die Großansicht nicht.
