### ISSUE TITLE
Insertion of a content slider element into an article leads to an error 

### ISSUE THREAD

**Issue by cafischer** [contao-themes-net/nature-theme-bundle#62]
I added a content slider with Content-Slider (Umschlag Anfang), Content-Slider (Umschlag Ende)and Slider-Element in between, but this resulted in an error:
`Compile Error: Declaration of ContaoThemesNet\NatureThemeBundle\Element\SliderElementNature::compile() must be compatible with ContaoThemesNet\ThemeComponentsBundle\Element\SliderElement::compile(): void`
Nature Theme Version: 1.4.3
Contao Version: 4.11.9

**Comment by seibtph** [comment]
Please update Nature Theme to version 1.10.0
