### ISSUE TITLE
Fehler beim speichern eines Formulars in Contao 5.04 und 5.06

### ISSUE THREAD

**Issue by bzaiser** [contao-themes-net/nature-theme-bundle#63]
## Bug description
Beim Speichern eines beliebigen ode auch neuen Formulars kommt der Fehler:
Contao\DcaLoader::{closure}(): Argument #2 ($dc) must be of type DataContainer, Contao\DC_Table given, called in /vendor/contao/core-bundle/contao/drivers/DC_Table.php on line 3203

## Steps to reproduce
neue Installation mit dem Natur Theme bei Strato mit  PHP Version 8.1.11
Formular der Beispiel / Demo Seite abspeichern

## Environment
gehostet bei Strato mit  PHP Version 8.1.11 Contao 5.04 Natur Theme Version 2.0.0
Der Paketmanager sagt es gibt einen Version 2.0.1 , aber bei der Installation sagt samphony keine Änderungen, dahe bleibt immer die Version 2.0.0

Bernd

**Comment by acht11** [comment]
Genau das gleiche Problem bei mir.
PHP 8.1.7
Theme 2.0.0
Contao 5.0.6
ALL-INKL

Josef

**Comment by bzaiser** [comment]
Hab den Fehler gefunden:
 in der Datei /vendor/pdir/css-style-selector-bundle/contao/dca
 
in Zeile 35  den Klassennamen "\DataContainer" gelöscht.

 vorher   function ($varValue, \DataContainer $dc) {
 nachher   function ($varValue, $dc) {

 Formular lässt sich nun speichern ;-)

**Comment by acht11** [comment]
Hallo Bernd,
welche Datei(n) meinst du?
Ich habe die Einträge in den forms und fom_fields gefunden.
Brachte aber keine Besserung.
Grüße

**Comment by acht11** [comment]
Contao-Manager -> Anwendungs Cache erneuern hilft.
Jetzt klappt das.
Danke und Sorry.

**Comment by MDevster** [comment]
Fixed in [Version 1.7.1 ](https://github.com/pdir/css-style-selector-bundle/releases/tag/1.7.1)of Css Style Selector Bundle, please update components.
