### ISSUE TITLE
Image alignment dosen't work

### ISSUE THREAD

**Issue by acht11** [contao-themes-net/nature-theme-bundle#64]
When I create a new Text with a picture, the picture alignment or the textflow will be ignored.
Just I have selected the content_element/text/simple_box_nature template. 
When I switch to the core template, it works.
How can I do it with the nature template?

![Bildausrichtung](https://user-images.githubusercontent.com/86398696/203350340-da4e07ff-f0a6-4bf2-bfac-0fb3f0fdd7a3.png)
with nature template
![Bildausrichtung1](https://user-images.githubusercontent.com/86398696/203350379-c3af60dd-13a0-4c1f-b782-c3ccf274c7f0.png)
witch core template
![Bildausrichtung2](https://user-images.githubusercontent.com/86398696/203351653-14ac0495-0856-4d35-a927-8c6c693ae279.png)

**Comment by seibtph** [comment]
Fixed in 2.1.0, please update!

**Comment by acht11** [comment]
Update not working.

 

 

 

$ /bin/php81 -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /www/htdocs/w0194201/contao5test.acht11.de/contao/public/contao-manager.phar.php composer install --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader

2

3Installing dependencies from lock file

4Verifying lock file contents can be installed on current platform.

5Package operations: 0 installs, 42 updates, 0 removals

6 - Upgrading symfony/string (v6.1.7 => v6.2.0): Extracting archive

7 - Upgrading symfony/http-foundation (v6.1.7 => v6.2.0): Extracting archive

8 - Upgrading symfony/event-dispatcher (v6.1.0 => v6.2.0): Extracting archive

9 - Upgrading symfony/var-dumper (v6.1.6 => v6.2.0): Extracting archive

10 - Upgrading symfony/error-handler (v6.1.7 => v6.2.0): Extracting archive

11 - Upgrading symfony/http-kernel (v6.1.7 => v6.1.8): Extracting archive

12 - Upgrading symfony/http-client (v6.1.7 => v6.2.0): Extracting archive

13 - Upgrading symfony/dom-crawler (v6.1.7 => v6.2.0): Extracting archive

14 - Upgrading symfony/yaml (v6.1.6 => v6.2.0): Extracting archive

15 - Upgrading symfony/uid (v6.1.5 => v6.2.0): Extracting archive

16 - Upgrading symfony/twig-bridge (v6.1.7 => v6.1.8): Extracting archive

17 - Upgrading symfony/filesystem (v6.1.5 => v6.2.0): Extracting archive

18 - Upgrading symfony/config (v6.1.3 => v6.2.0): Extracting archive

19 - Upgrading symfony/translation (v6.1.6 => v6.2.0): Extracting archive

20 - Upgrading symfony/password-hasher (v6.1.3 => v6.2.0): Extracting archive

21 - Upgrading symfony/security-core (v6.1.7 => v6.2.0): Extracting archive

22 - Upgrading symfony/property-info (v6.1.7 => v6.2.0): Extracting archive

23 - Upgrading symfony/property-access (v6.1.7 => v6.2.0): Extracting archive

24 - Upgrading symfony/security-csrf (v6.1.0 => v6.2.0): Extracting archive

25 - Upgrading symfony/routing (v6.1.7 => v6.2.0): Extracting archive

26 - Upgrading symfony/process (v6.1.3 => v6.2.0): Extracting archive

27 - Upgrading symfony/monolog-bridge (v6.1.2 => v6.2.0): Extracting archive

28 - Upgrading symfony/mime (v6.1.7 => v6.2.0): Extracting archive

29 - Upgrading symfony/mailer (v6.1.7 => v6.2.0): Extracting archive

30 - Upgrading symfony/lock (v6.1.7 => v6.2.0): Extracting archive

31 - Upgrading symfony/intl (v6.1.7 => v6.2.0): Extracting archive

32 - Upgrading symfony/finder (v6.1.3 => v6.2.0): Extracting archive

33 - Upgrading symfony/var-exporter (v6.1.3 => v6.2.0): Extracting archive

34 - Upgrading symfony/cache (v6.1.7 => v6.2.0): Extracting archive

35 - Upgrading symfony/framework-bundle (v6.1.7 => v6.1.8): Extracting archive

36 - Upgrading symfony/expression-language (v6.1.6 => v6.2.0): Extracting archive

37 - Upgrading symfony/doctrine-bridge (v6.1.7 => v6.1.8): Extracting archive

38 - Upgrading symfony/console (v6.1.7 => v6.2.0): Extracting archive

39 - Upgrading symfony/asset (v6.1.5 => v6.2.0): Extracting archive

40 - Upgrading symfony/options-resolver (v6.1.0 => v6.2.0): Extracting archive

41 - Upgrading league/flysystem (3.10.3 => 3.11.0): Extracting archive

42 - Upgrading symfony/templating (v6.1.3 => v6.2.0): Extracting archive

43 - Upgrading friendsofsymfony/http-cache (2.14.2 => 2.15.0): Extracting archive

44 - Upgrading friendsofsymfony/http-cache-bundle (2.13.0 => 2.14.0): Extracting archive

45 - Upgrading contao-themes-net/nature-theme-bundle (2.0.0 => 2.1.0): Extracting archive

46 - Upgrading contao/conflicts (dev-main 96abbf1 => dev-main e00a47a)

47 - Upgrading symfony/stopwatch (v6.1.5 => v6.2.0): Extracting archive

48Generating optimized autoload files

49contao/manager-plugin: Dumping generated plugins file...

50contao/manager-plugin: ...done dumping generated plugins file

51Class Contao\ManagerPlugin\PluginLoader located in ./vendor/contao/manager-plugin/src/Resources/PluginLoader.php does not comply with psr-4 autoloading standard. Skipping.

52107 packages you are using are looking for funding.

53Use the `composer fund` command to find out more!

54> @php vendor/bin/contao-setup

55

56Fatal error: During class fetch: Uncaught ReflectionException: Class "ContaoThemesNet\ZeroOneThemeBundle\Migration\MigrationHelperTrait" not found while loading "ContaoThemesNet\NatureThemeBundle\Migration\InitialDemoDataMigration". in /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/composer/ClassLoader.php:571

57Stack trace:

58#0 [internal function]: Composer\Autoload\ClassLoader->loadClass('ContaoThemesNet...')

59#1 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/config/Resource/ClassExistenceResource.php(76): class_exists('ContaoThemesNet...')

60#2 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/ContainerBuilder.php(346): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)

61#3 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/FileLoader.php(217): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('ContaoThemesNet...')

62#4 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/FileLoader.php(105): Symfony\Component\DependencyInjection\Loader\FileLoader->findClasses('ContaoThemesNet...', '../src/Migratio...', Array, Object(Symfony\Component\DependencyInjection\Compiler\RegisterAutoconfigureAttributesPass))

63#5 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(695): Symfony\Component\DependencyInjection\Loader\FileLoader->registerClasses(Object(Symfony\Component\DependencyInjection\Definition), 'ContaoThemesNet...', '../src/Migratio...', NULL)

64#6 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(256): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseDefinition('ContaoThemesNet...', Array, '/www/htdocs/w01...', Array, false, true)

65#7 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(176): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseDefinitions(Array, '/www/htdocs/w01...')

66#8 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(132): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadContent(Array, '/www/htdocs/w01...')

67#9 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/contao-themes-net/nature-theme-bundle/src/DependencyInjection/ContaoThemesNetNatureThemeExtension.php(34): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')

68#10 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): ContaoThemesNet\NatureThemeBundle\DependencyInjection\ContaoThemesNetNatureThemeExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))

69#11 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(42): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Contao\ManagerPlugin\Config\ContainerBuilder))

70#12 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Compiler/Compiler.php(73): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Contao\ManagerPlugin\Config\ContainerBuilder))

71#13 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/ContainerBuilder.php(716): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Contao\ManagerPlugin\Config\ContainerBuilder))

72#14 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/http-kernel/Kernel.php(538): Symfony\Component\DependencyInjection\ContainerBuilder->compile()

73#15 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(288): Symfony\Component\HttpKernel\Kernel->initializeContainer()

74#16 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/http-kernel/Kernel.php(767): Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer()

75#17 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()

76#18 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/framework-bundle/Console/Application.php(166): Symfony\Component\HttpKernel\Kernel->boot()

77#19 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/framework-bundle/Console/Application.php(72): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()

78#20 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/console/Application.php(168): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

79#21 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/contao/manager-bundle/bin/contao-setup(44): Symfony\Component\Console\Application->run()

80#22 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/bin/contao-setup(120): include('/www/htdocs/w01...')

81#23 {main} in /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/contao-themes-net/nature-theme-bundle/src/Migration/InitialDemoDataMigration.php on line 28

82PHP Fatal error: During class fetch: Uncaught ReflectionException: Class "ContaoThemesNet\ZeroOneThemeBundle\Migration\MigrationHelperTrait" not found while loading "ContaoThemesNet\NatureThemeBundle\Migration\InitialDemoDataMigration". in /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/composer/ClassLoader.php:571

83Stack trace:

84#0 [internal function]: Composer\Autoload\ClassLoader->loadClass('ContaoThemesNet...')

85#1 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/config/Resource/ClassExistenceResource.php(76): class_exists('ContaoThemesNet...')

86#2 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/ContainerBuilder.php(346): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)

87#3 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/FileLoader.php(217): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('ContaoThemesNet...')

88#4 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/FileLoader.php(105): Symfony\Component\DependencyInjection\Loader\FileLoader->findClasses('ContaoThemesNet...', '../src/Migratio...', Array, Object(Symfony\Component\DependencyInjection\Compiler\RegisterAutoconfigureAttributesPass))

89#5 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(695): Symfony\Component\DependencyInjection\Loader\FileLoader->registerClasses(Object(Symfony\Component\DependencyInjection\Definition), 'ContaoThemesNet...', '../src/Migratio...', NULL)

90#6 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(256): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseDefinition('ContaoThemesNet...', Array, '/www/htdocs/w01...', Array, false, true)

91#7 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(176): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseDefinitions(Array, '/www/htdocs/w01...')

92#8 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(132): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadContent(Array, '/www/htdocs/w01...')

93#9 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/contao-themes-net/nature-theme-bundle/src/DependencyInjection/ContaoThemesNetNatureThemeExtension.php(34): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')

94#10 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): ContaoThemesNet\NatureThemeBundle\DependencyInjection\ContaoThemesNetNatureThemeExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))

95#11 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(42): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Contao\ManagerPlugin\Config\ContainerBuilder))

96#12 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/Compiler/Compiler.php(73): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Contao\ManagerPlugin\Config\ContainerBuilder))

97#13 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/dependency-injection/ContainerBuilder.php(716): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Contao\ManagerPlugin\Config\ContainerBuilder))

98#14 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/http-kernel/Kernel.php(538): Symfony\Component\DependencyInjection\ContainerBuilder->compile()

99#15 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(288): Symfony\Component\HttpKernel\Kernel->initializeContainer()

100#16 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/http-kernel/Kernel.php(767): Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer()

101#17 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()

102#18 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/framework-bundle/Console/Application.php(166): Symfony\Component\HttpKernel\Kernel->boot()

103#19 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/framework-bundle/Console/Application.php(72): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()

104#20 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/symfony/console/Application.php(168): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

105#21 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/contao/manager-bundle/bin/contao-setup(44): Symfony\Component\Console\Application->run()

106#22 /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/bin/contao-setup(120): include('/www/htdocs/w01...')

107#23 {main} in /www/htdocs/w0194201/contao5test.acht11.de/contao/vendor/contao-themes-net/nature-theme-bundle/src/Migration/InitialDemoDataMigration.php on line 28

108Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255

109

110# Process terminated with exit code 255

111# Result: Unknown error

 

 

Von: Philipp Seibt ***@***.***> 
Gesendet: Dienstag, 6. Dezember 2022 16:43
An: contao-themes-net/nature-theme-bundle ***@***.***>
Cc: acht11 ***@***.***>; Author ***@***.***>
Betreff: Re: [contao-themes-net/nature-theme-bundle] Image alignment dosen't work (Issue #64)

 

Fixed in 2.1.0, please update!

**Comment by MDevster** [comment]
Fixed in 2.1.1, please update.

**Comment by acht11** [comment]
Hallo Zusammen,

 

jetzt läuft es. 

 

Vielen Dank

 

Grüße

 

Josef

 

 

Von: Mathias Arzberger ***@***.***> 
Gesendet: Donnerstag, 8. Dezember 2022 08:34
An: contao-themes-net/nature-theme-bundle ***@***.***>
Cc: acht11 ***@***.***>; Author ***@***.***>
Betreff: Re: [contao-themes-net/nature-theme-bundle] Image alignment dosen't work (Issue #64)

 

Closed #64 <https://github.com/contao-themes-net/nature-theme-bundle/issues/64>  as completed.
