### ISSUE TITLE
Keep your Megamenue opened at first Klick on it

### ISSUE THREAD

**Issue by witzker** [contao-themes-net/nature-theme-bundle#72]
## Description
 **sorry, not clever enough!**

Hi, I hope that is the right place for my request!
I'm just switching over from Joomla and I think that your template will meet my demands.
As I'm total new with this stuff, I would like to ask a question about your Megamenue
I noticed when hoovering over the menu entry module after clicking Megamenue the Megamenue is displayed until you leave the menu entry - Right?
What I want to achieve is:
When adding new Main menu entry and the visitor of my homepage klicks on it the Megamenue shall be opened AND stays open
so even if the visitor when visiting some sub entry of the Megamenue  is able to see the still opened Megamenu sub entries and easily can switch to another subentry if he does not find the desired information on the first click.
Without going back to open the Megamenue again

I hope You can understand my request.
This menu **should stay opened** on first click
![image](https://user-images.githubusercontent.com/4120266/222808666-45d3bf99-cf84-47f0-93df-e37c00e61477.png)
 Hope for Instructions
Many THX

**Comment by MDevster** [comment]
We'll take a look at it, Philipp will get back to you here on Monday.

**Comment by witzker** [comment]
Great news [MDevster](https://github.com/MDevster) many THX for taking care

**Comment by seibtph** [comment]
Maybe this jquery code helps you:

```
<script>
jQuery(document).ready(function($) {
  $('.megamenu .level_1 > .submenu > a').click(function(e) {
    if($(this).next().css('display') === 'flex') {
      $(this).next().css('display', 'none');
    } else {
      $('.navbar-dropdown.level_2').css('display', 'none');
      $(this).next().css('display', 'flex');
    }
    e.preventDefault();
  });
  
  $('body').click(function(e) {
    if($(e.target).closest('.megamenu').length === 0) {
      $('.navbar-dropdown.level_2').css('display', 'none');
    }
  });
});
</script>
```

When the visitor click a menu entry the megamenu shall be opened.

Add folowing scss to prevent the mouse hover:

```
.megamenu .navbar-item:hover .navbar-dropdown.level_2 {
    display: none;
}
```
