### ISSUE TITLE
How to leave the accordeon closed when loading the page

### ISSUE THREAD

**Issue by witzker** [contao-themes-net/nature-theme-bundle#73]
Hi,
I found This, but I don't know how to set the accordeon closed
https://pdir.de/docs/de/contao/themes/zeroone/elements/accordions/
When I set this as read in a contao forum, it does not work any more
![image](https://user-images.githubusercontent.com/4120266/222937196-8fe339c0-3cd0-47a6-8292-61e531a4d985.png)

I hope you can tell me what to put where to achieve this
Many THX

PS: Is there also the possibility to have some "arrow down" so also inexperienced user can see that there is more info on the website when he clicks on it?

**Comment by seibtph** [comment]
Add the following line to the j_accordion.html5 template: `active: false,`

e.g.

```

<script src="<?= $this->asset('js/jquery-ui.min.js', 'contao-components/jquery-ui') ?>"></script>
<script>
  jQuery(function($) {
    $(document).accordion({
      // Put custom options here
      heightStyle: 'content',
      header: '.toggler',
      active: false,
      collapsible: true,
      create: function(event, ui) {
        ui.header.addClass('active');
        $('.toggler').attr('tabindex', 0);
      },
      activate: function(event, ui) {
        ui.newHeader.addClass('active');
        ui.oldHeader.removeClass('active');
        $('.toggler').attr('tabindex', 0);
      }
    });
  });
</script>

```

**Comment by seibtph** [comment]
Here is a example to add arrows for the accordion. We can add this as feature to the next theme version.

```
.ui-accordion-header {
    display: flex;
    justify-content: space-between;
    flex-direction: row-reverse;
    
    .ui-accordion-header-icon:before {
        content: "\f063";
        font: var(--fa-font-solid);
    }
    
    &.active .ui-accordion-header-icon:before {
        content: "\f062";
    }
}
```

![image](https://user-images.githubusercontent.com/17127525/225078827-16673716-fd0d-4ad4-809d-185e05735b0a.png)
