### ISSUE TITLE
Show article in Tabs

### ISSUE THREAD

**Issue by witzker** [contao-themes-net/nature-theme-bundle#74]
Hi, I want to show articles in Tabs
How to achieve this?

**Comment by seibtph** [comment]
You can use the element type article (include elements) and create this element inside the tabs container.

![image2](https://user-images.githubusercontent.com/17127525/225073897-22b6a346-5040-471a-8115-509c249fce36.png)

![image](https://user-images.githubusercontent.com/17127525/225073902-2e75922e-88cd-4de0-af83-0c47e7d27fd7.png)
