### ISSUE TITLE
Headerbild wird nicht geladen

### ISSUE THREAD

**Issue by Steffen517** [contao-themes-net/nature-theme-bundle#75]
Hallo zusammen,

bei mir wird das Headerbild bei der Event Detail Ansicht nicht geladen.
Herausgefunden habe ich das der falsche Pfad genommen wird:

style="background-image:url('//files/Images/Kirchentag/2023/dekt2023.jpg')" <-- falsch
style="background-image:url('/files/Images/Kirchentag/2023/dekt2023.jpg')" <-- richtig.

Hier wird ein Schrägstrich zu viel geladen.
Gibt es eine Lösung für das Problem?

Gruß Steffen

**Comment by seibtph** [comment]
Wird in der nächsten Version behoben.

Den Schrägstrich kannst du im Template event_full_nature_header.html5 entfernen.
