### ISSUE TITLE
Dateiverwaltung files/naturetheme/scss/_custom_variables.scss

### ISSUE THREAD

**Issue by Premala108** [contao-themes-net/nature-theme-bundle#79]
Hello,

the system does not accept my change of colour in above file:

* ====================== */
/*        Footer          */
/* ====================== */

$footer-background-color: #8A2BE2;
//$footer-color: $white-ter;
//$footer-padding: 40px 0;

Is this the right code?
What is wrong?

Kind regards from Germany
Premala

**Comment by Premala108** [comment]
I found the solution:
it's a problem of firefox
with IE i can see the color

**Comment by seibtph** [comment]
Maybe it's a cache problem? Can you reload the page with Ctrl + F5?
