### ISSUE TITLE
Nature Theme Contao V5.3 Feldfehler

### ISSUE THREAD

**Issue by chrnit** [contao-themes-net/nature-theme-bundle#87]
In Contao V5.3 wirft das Nature Theme nach Installation über den Manager und Upload der CTO-Datei als Theme folgende Fehler:

```

Die Datei nature_theme_contao_4.13.cto wurde erfolgreich hochgeladen.


Tabellen und Felder

Das Feld tl_theme.vars fehlt in der Datenbank und wird daher nicht importiert.

Das Feld tl_module.url fehlt in der Datenbank und wird daher nicht importiert.

Das Feld tl_module.orderSRC fehlt in der Datenbank und wird daher nicht importiert.

Das Feld tl_module.guests fehlt in der Datenbank und wird daher nicht importiert.

Das Feld tl_module.news_metaFields fehlt in der Datenbank und wird daher nicht importiert.

Das Feld tl_layout.stylesheet fehlt in der Datenbank und wird daher nicht importiert.

Das Feld tl_layout.loadingOrder fehlt in der Datenbank und wird daher nicht importiert.
```

**Comment by seibtph** [comment]
Hast du bereits Inhalte auf deiner Seite oder warum versucht du die cto-Datei zu importieren? Die ist noch für Contao 4.13, für Contao 5.3 gibt es aktuell noch keine. Wenn du aber eine leere Datenbank hast, kannst du die Demo importieren, indem du die Datenbank im Contao Manager aktualisierst.

**Comment by chrnit** [comment]
Ich experimentierte grad neu an der Seite und habe nur eine Artikel angelegt, hatte aber von eurem Guide her verstanden, dass, wenn ich schon Inhalte habe, lieber die cto Datei importieren sollte. 

Kannst du den Prozess des Demo-Imports genauer beschreiben?

Ich denke, mir ist noch unklar, wie ich das Theme richtig nutze - bisher habe ich im contao manager das nature Theme installiert, die DB entsprechend geupdated, das Theme freischalten lassen und sehe jetzt aber nichts davon im Frontend.

**Comment by chrnit** [comment]
Ich würde mich über eine Rückmeldung freuen, ansonsten ich das Theme nicht nutzen kann.

**Comment by seibtph** [comment]
Am einfachsten wäre es, wenn du eine leere Datenbank hast. Wenn du bisher nicht viel angelegt hast, wäre das wohl der einfachste und schnellste Weg die Datenbank nochmal zu leeren (bis auf die tl_user). Dann kannst du die Demo ganz einfach über den Contao Manager importieren, wenn du die Datenbank aktualisierst (unter Systemwartung). Es sollte eine Datenbank-Migration angezeigt werden, wie in der Dokumentation zu sehen: https://pdir.de/docs/de/contao/themes/nature/installation/

**Comment by chrnit** [comment]
Ok, das habe ich jetzt gemacht und sehe bei Klick auf Preview " Es ist ein Fehler aufgetreten. Was ist das Problem? Bei der Ausführung des Skriptes ist ein Fehler aufgetreten. Irgendetwas funktioniert nicht richtig."

Was fehlt jetzt noch?

**Comment by MDevster** [comment]
Hast du einen Link + Contao Admin für mich, bitte per Mail an support  @ pdir . de
Dann schau ich mal wo das Problem ist.

**Comment by chrnit** [comment]
Ich habe das Problem eben selbst gefunden - alle Caches leeren und neu aufbauen hat geholfen. 

Danke Euch für die Unterstützung!
