### ISSUE TITLE
Installation NATURE Theme

### ISSUE THREAD

**Issue by SITsup** [contao-themes-net/nature-theme-bundle#93]
hello
I have contao 5.4 on a debian server with php 8+
once with the Contao demo 2 times without the demo
 so completely empty.
then I tried to install the NATURE theme each time.
unfortunately each time I got the same error message and the complete installation did not work anymore. The backend no longer worked and the contao manager only worked in safe mode. (Repair did not work)

Error message:
$ /opt/plesk/php/8.3/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=UTC /var/www/vhosts/blumenladen.zuerich/httpdocs/public/contao-manager.phar.php composer install --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
contao/manager-plugin: Dumping generated plugins file...
contao/manager-plugin: ...done dumping generated plugins file
Fatal error: Declaration of ContaoThemesNet\FontAwesomeInserttagBundle\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder in /var/www/vhosts/blumenladen.zuerich/httpdocs/vendor/contao-themes-net/font-awesome-inserttag-bundle/src/DependencyInjection/Configuration.php on line 32
116 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php vendor/bin/contao-setup
PHP Fatal error:  Declaration of ContaoThemesNet\FontAwesomeInserttagBundle\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder in /var/www/vhosts/blumenladen.zuerich/httpdocs/vendor/contao-themes-net/font-awesome-inserttag-bundle/src/DependencyInjection/Configuration.php on line 32
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255
# Process terminated with exit code 255
# Result: Unknown error

I hope you can help me.
best regards albert

**Comment by seibtph** [comment]
Can you please post your composer.json? Thanks

**Comment by SITsup** [comment]
Hi
Thank you for your enquiry
Please find enclosed the file composer.json

Best regards
Albert

******************************************************************************
¦ swissit ag, emil-staub-strasse 2, ch-8708 männedorf
¦ E-Mail: ***@***.******@***.***>
******************************************************************************

Von: Philipp Seibt ***@***.***>
Gesendet: Freitag, 13. September 2024 11:05
An: contao-themes-net/nature-theme-bundle ***@***.***>
Cc: Swissit AG EXCH ***@***.***>; Author ***@***.***>
Betreff: Re: [contao-themes-net/nature-theme-bundle] Installation NATURE Theme (Issue #93)


Can you please post your composer.json? Thanks

**Comment by seibtph** [comment]
Sorry, I don't see the enclosure.

**Comment by SITsup** [comment]
Hi Philipp
Sorry, I have attached the file again
Below you can see the content of the file

Mit freundlichen Grüssen
A. Spaar

******************************************************************************
¦ swissit ag, emil-staub-strasse 2, ch-8708 männedorf
¦ E-Mail: ***@***.******@***.***>
******************************************************************************

Von: Philipp Seibt ***@***.***>
Gesendet: Freitag, 13. September 2024 14:26
An: contao-themes-net/nature-theme-bundle ***@***.***>
Cc: Swissit AG EXCH ***@***.***>; Author ***@***.***>
Betreff: Re: [contao-themes-net/nature-theme-bundle] Installation NATURE Theme (Issue #93)


Sorry, I don't see the enclosure.

**Comment by SITsup** [comment]
Hi Philipp
Sorry, I have attached the file again
Below you can see the content of the file

{
    "type": "project",
    "require": {
        "contao/conflicts": ***@***.***",
        "contao/manager-bundle": "5.4.*",
        "contao/calendar-bundle": "5.4.*",
        "contao/comments-bundle": "5.4.*",
        "contao/faq-bundle": "5.4.*",
        "contao/listing-bundle": "5.4.*",
        "contao/news-bundle": "5.4.*",
        "contao/newsletter-bundle": "5.4.*"
    },
    "extra": {
        "public-dir": "public",
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            ***@***.*** vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            ***@***.*** vendor/bin/contao-setup"
        ]
    }
}

Best regards
Albert

******************************************************************************
¦ swissit ag, emil-staub-strasse 2, ch-8708 männedorf
¦ E-Mail: ***@***.******@***.***>
******************************************************************************

Von: Philipp Seibt ***@***.***>
Gesendet: Freitag, 13. September 2024 14:26
An: contao-themes-net/nature-theme-bundle ***@***.***>
Cc: Swissit AG EXCH ***@***.***>; Author ***@***.***>
Betreff: Re: [contao-themes-net/nature-theme-bundle] Installation NATURE Theme (Issue #93)


Sorry, I don't see the enclosure.

**Comment by kmielke** [comment]
i have the same problem. theme installs without demo data.

**Comment by kmielke** [comment]
Problem still exists with Theme Version 2.3.3. I am using Contao LTS 5.3.17
